# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.1'

gem 'activesupport'

group :test do
  gem 'test-unit'
end

group :development do
  gem 'rubocop'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end
